CODE_OF_CONDUCT.md

Add a Global Code of Conduct for Jenkins infrastructure repositories

---

SUPPORT.md

Add a global Support page for Jenkins Infra repositories

---

CONTRIBUTING.md

Introduce global CONTRIBUTING metadata inside the GitHub organization

---

CONTRIBUTING.md

Add a link to the newcomers chat in the CONTRIBUTING template

---

FUNDING.yml

JEP draft: https://github.com/jenkinsci/jep/pull/286

[JEP-15] - Add Funding page for the Jenkins Infrastructure GitHub org

---

.github/release-drafter.yml

Mostly the same as jenkinsci, added a couple of new options with version resolution to try out

Add release drafter for infra

---

SUPPORT.md
profile/README.md

Close https://github.com/jenkins-infra/helpdesk/issues/2962

Create jenkins-infra org profile

---

CONTRIBUTING.md

Title says all, additionally update the mailing list URL.

chore: Exchange freenode with libera URL

---

profile/README.md

Equivalent of https://github.com/jenkinsci/.github/pull/96 for jenkins-infra org
cc @jmMeessen

Add Hacktoberfest info

---

profile/README.md

<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

chore: add spacing between Hacktobertfest logo & description

---

profile/README.md

Same as https://github.com/jenkinsci/.github/pull/100

chore: remove Hacktoberfest 2022 from GitHub profile

---

profile/README.md

Same as https://github.com/jenkinsci/.github/pull/101 for @jenkins-infra

Add Jenkins Board and Officer Elections 2022 info

---

profile/README.md

Same as https://github.com/jenkinsci/.github/pull/102

Highlight election part

---

profile/README.md

Follow-up of https://github.com/jenkins-infra/jenkins.io/pull/5700

Jenkins Elections 2022 results announcement

---

profile/README.md

One more location to announce the scheduled downtime.

Announce repo.jenkins-ci.org upgrade

---

profile/README.md

Add a separation between announcement and next section

---

profile/README.md

Together with Alyssa Tong, I am proposing an update to the Jenkinsci organisation readme to announce the Jenkins Contributor Awards 2023 nomination and voting process.

[info] Add info on Contributors Awards 2023 in README.md

---

profile/README.md

Voting closed yesterday.
Same as https://github.com/jenkinsci/.github/pull/120

Remove contributor awards text

---

profile/README.md

Saw this on a plugin contributing doc, opening a PR in draft for discussions about adding something similar on the org profile, this certainly can be formulated in a better way.

Add encouragement to participate on jenkins-infra org profile

---

.github/ISSUE_TEMPLATE/1-report-bug.yml
.github/ISSUE_TEMPLATE/config.yml

Actually include a link to the Help Desk as I initially wrote in the issue, and small improvements regarding bug report instructions.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3

Include a link to jenkins-infra/helpdesk and cleanup bug report instructions

---

profile/README.md

Follow-up of:
- https://github.com/jenkins-infra/jenkins.io/pull/7042
Related:
- https://github.com/jenkins-infra/jenkins.io/pull/7075
- https://github.com/jenkinsci/.github/pull/133

Add Contributors Awards 2024 to @jenkins-infra org profile

---

profile/README.md

Remove elections

---

profile/README.md

Add Contributors Awards 2025 to @jenkins-infra org profile
